#update time: 2025-05-14
mixed-port: 7890
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
dns:
  enable: true
  ipv6: false
  use-hosts: false
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - tls://dot.pub
    - tls://dns.alidns.com
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback-policy: any
  fake-ip-filter: []
  use-system-hosts: false
  proxy-server-nameserver:
    - tls://dot.pub
    - tls://dns.alidns.com
  direct-nameserver:
    - tls://dot.pub
    - tls://dns.alidns.com
  nameserver-policy: {}
  respect-rules: true
proxy-providers:
  vansour:
    type: http
    url: https://sub.vansour.top/vansour
    path: ./proxy_providers/vansour.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  主用 01:
    type: http
    url: https://sub.vansour.top/vansour
    filter: 主用 01
    path: ./proxy_providers/vansour.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  主用 02:
    type: http
    url: https://sub.vansour.top/vansour
    filter: 主用 02
    path: ./proxy_providers/vansour.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  主用 03:
    type: http
    url: https://sub.vansour.top/vansour
    filter: 主用 03
    path: ./proxy_providers/vansour.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  quickcat:
    type: http
    url: https://sub.vansour.top/quickcat
    path: ./proxy_providers/quickcat.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: MainNode
    type: select
    use:
      - vansour
    proxies:
      - 主用 05 美国 00
      - 主用 05 英国 00
      - 主用 05 香港 00
      - 主用 05 日本 00
      - 主用 05 韩国 00
      - 主用 05 新加坡 00
  - name: Youtube
    type: select
    proxies:
      - 主用 05 美国 00
      - 主用 05 英国 00
      - 主用 05 香港 00
      - 主用 05 日本 00
      - 主用 05 韩国 00
      - 主用 05 新加坡 00
  - name: Github
    type: select
    use:
      - 主用 01
  - name: Cloudflare
    type: select
    use:
      - 主用 01
  - name: Openai
    type: select
    use:
      - 主用 01
  - name: HK
    type: select
    proxies:
      - 香港
      - MainNode
  - name: 香港
    type: select
    use:
      - vansour
    filter: 香港
    hidden: true
  - name: 主用 05 美国 00
    type: load-balance
    use:
      - quickcat
    filter: 美国
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 05 英国 00
    type: load-balance
    use:
      - quickcat
    filter: 英国
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 05 香港 00
    type: load-balance
    use:
      - quickcat
    filter: 香港
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 05 日本 00
    type: load-balance
    use:
      - quickcat
    filter: 日本
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 05 韩国 00
    type: load-balance
    use:
      - quickcat
    filter: 韩国
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 05 新加坡 00
    type: load-balance
    use:
      - quickcat
    filter: 新加坡
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
rule-providers:
  domain_category-ads-all:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/category-ads-all.yaml
    path: ./rule_providers/domain_category-ads-all.yaml
    interval: 86400
  domain_cn:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/cn.yaml
    path: ./rule_providers/domain_cn.yaml
    interval: 86400
  domain_youtube:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/youtube.yaml
    path: ./rule_providers/domain_youtube.yaml
    interval: 86400
  domain_github:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/github.yaml
    path: ./rule_providers/domain_github.yaml
    interval: 86400
  domain_cloudflare:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/cloudflare.yaml
    path: ./rule_providers/domain_cloudflare.yaml
    interval: 86400
  domain_openai:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/openai.yaml
    path: ./rule_providers/domain_openai.yaml
    interval: 86400
  ipcidr_hk:
    type: http
    behavior: ipcidr
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geoip/hk.yaml
    path: ./rule_providers/ipcidr_hk.yaml
    interval: 86400
  ipcidr_cn:
    type: http
    behavior: ipcidr
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geoip/cn.yaml
    path: ./rule_providers/ipcidr_cn.yaml
    interval: 86400
rules:
  - RULE-SET,domain_category-ads-all,REJECT
  - RULE-SET,domain_cn,DIRECT
  - RULE-SET,domain_youtube,Youtube
  - RULE-SET,domain_github,Github
  - RULE-SET,domain_cloudflare,Cloudflare
  - RULE-SET,domain_openai,Openai
  - RULE-SET,ipcidr_hk,HK
  - RULE-SET,ipcidr_cn,DIRECT
  - MATCH,MainNode
unified-delay: true
tcp-concurrent: true
