mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
unified-delay: true
tcp-concurrent: true

dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://dns.google/dns-query
  fallback:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 224.0.0.0/4

proxy-providers:
  V1:
    type: http
    url: https://sub.vansour.top/v1
    path: ./proxy_providers/v1.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  V2:
    type: http
    url: https://sub.vansour.top/v2
    path: ./proxy_providers/v2.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: 主用
    type: select
    use:
      - V1
    proxies:
      - 美国
      - 英国
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 新加坡

  - name: Youtube
    type: select
    use:
      - V1
    proxies:
      - 美国
      - 英国
      - 香港
      - 台湾
      - 日本
      - 韩国
      - 新加坡

  - name: 美国
    type: load-balance
    filter: (?i)美国
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    use:
      - V2

  - name: 英国
    type: load-balance
    filter: (?i)英国
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    use:
      - V2

  - name: 香港
    type: load-balance
    filter: (?i)香港
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    use:
      - V2

  - name: 台湾
    type: load-balance
    filter: (?i)台湾
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    use:
      - V2

  - name: 日本
    type: load-balance
    filter: (?i)日本
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    use:
      - V2

  - name: 韩国
    type: load-balance
    filter: (?i)韩国
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    use:
      - V2

  - name: 新加坡
    type: load-balance
    filter: (?i)新加坡
    strategy: round-robin
    url: http://www.gstatic.com/generate_204
    use:
      - V2

rule-providers:
  domain_category-ads-all:
    type: http
    behavior: domain
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geosite/site_category-ads-all.txt
    path: ./rule_providers/site_category-ads-all.yaml
    interval: 86400

  ip_private:
    type: http
    behavior: ipcidr
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geoip/ip_private.txt
    path: ./rule_providers/ip_private.yaml
    interval: 86400

  ip_cn:
    type: http
    behavior: ipcidr
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geoip/ip_cn.txt
    path: ./rule_providers/ip_cn.yaml
    interval: 86400

  domain_youtube:
    type: http
    behavior: domain
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geosite/site_youtube.txt
    path: ./rule_providers/site_youtube.yaml
    interval: 86400

rules:
  - RULE-SET,ip_private,DIRECT
  - RULE-SET,ip_cn,DIRECT
  - RULE-SET,domain_category-ads-all,REJECT
  - RULE-SET,domain_youtube,Youtube
  - MATCH,主用
