#update time: 2025/05/08
mixed-port: 7890
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
dns:
  enable: true
  ipv6: false
  use-hosts: false
  default-nameserver:
    - 119.29.29.29
  nameserver:
    - https://dns.google/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback:
    - https://doh.pub/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 224.0.0.0/4
  fallback-policy: any
  fake-ip-filter: []
  use-system-hosts: false
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy: {}
  respect-rules: false
proxy-providers:
  hkpre:
    type: http
    url: https://sub.vansour.top/hkpre
    path: ./proxy_providers/hkpre.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  uspre:
    type: http
    url: https://sub.vansour.top/uspre
    path: ./proxy_providers/uspre.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  usord:
    type: http
    url: https://sub.vansour.top/usord
    path: ./proxy_providers/usord.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  V1:
    type: http
    url: https://sub.vansour.top/v1
    path: ./proxy_providers/v1.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  V2:
    type: http
    url: https://sub.vansour.top/v2
    path: ./proxy_providers/v2.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: MainNode
    type: select
    use:
      - V1
    proxies:
      - 主用 03 美国 00
      - 主用 03 英国 00
      - 主用 03 香港 00
      - 主用 03 日本 00
      - 主用 03 韩国 00
      - 主用 03 新加坡 00
  - name: Youtube
    type: select
    proxies:
      - 主用 03 美国 00
      - 主用 03 英国 00
      - 主用 03 香港 00
      - 主用 03 日本 00
      - 主用 03 韩国 00
      - 主用 03 新加坡 00
  - name: Github
    type: select
    use:
      - hkpre
      - uspre
  - name: Cloudflare
    type: select
    use:
      - hkpre
      - uspre
  - name: Openai
    type: select
    use:
      - uspre
  - name: HK
    type: select
    use:
      - hkpre
    proxies:
      - MainNode
  - name: 主用 03 美国 00
    type: load-balance
    use:
      - V2
    filter: 美国
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 03 英国 00
    type: load-balance
    use:
      - V2
    filter: 英国
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 03 香港 00
    type: load-balance
    use:
      - V2
    filter: 香港
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 03 日本 00
    type: load-balance
    use:
      - V2
    filter: 日本
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 03 韩国 00
    type: load-balance
    use:
      - V2
    filter: 韩国
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
  - name: 主用 03 新加坡 00
    type: load-balance
    use:
      - V2
    filter: 新加坡
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true
rule-providers:
  domain_category-ads-all:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/category-ads-all.yaml
    path: ./rule_providers/domain_category-ads-all.yaml
    interval: 86400
  domain_cn:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/cn.yaml
    path: ./rule_providers/domain_cn.yaml
    interval: 86400
  domain_youtube:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/youtube.yaml
    path: ./rule_providers/domain_youtube.yaml
    interval: 86400
  domain_github:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/github.yaml
    path: ./rule_providers/domain_github.yaml
    interval: 86400
  domain_cloudflare:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/cloudflare.yaml
    path: ./rule_providers/domain_cloudflare.yaml
    interval: 86400
  domain_openai:
    type: http
    behavior: domain
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geosite/openai.yaml
    path: ./rule_providers/domain_openai.yaml
    interval: 86400
  ipcidr_hk:
    type: http
    behavior: ipcidr
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geoip/hk.yaml
    path: ./rule_providers/ipcidr_hk.yaml
    interval: 86400
  ipcidr_cn:
    type: http
    behavior: ipcidr
    url: https://dl.vansour.top/https://raw.githubusercontent.com/vansour/geo-rules/refs/heads/main/geo/geoip/cn.yaml
    path: ./rule_providers/ipcidr_cn.yaml
    interval: 86400
rules:
  - RULE-SET,domain_category-ads-all,REJECT
  - RULE-SET,domain_cn,DIRECT
  - RULE-SET,domain_youtube,Youtube
  - RULE-SET,domain_github,Github
  - RULE-SET,domain_cloudflare,Cloudflare
  - RULE-SET,domain_openai,Openai
  - RULE-SET,ipcidr_hk,HK
  - RULE-SET,ipcidr_cn,DIRECT
  - MATCH,MainNode
unified-delay: true
tcp-concurrent: true
