mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: false
  use-hosts: true
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://dns.google/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fallback:
    - https://dns.alidns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 224.0.0.0/4
  # 可选，自动切换fallback策略
  fallback-policy: 'any'

# 代理订阅
proxy-providers:
  V1:
    type: http
    url: https://sub.vansour.top/v1
    path: ./proxy_providers/v1.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  hkpre:
    type: http
    url: https://sub.vansour.top/hkpre
    path: ./proxy_providers/hkpre.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  uspre:
    type: http
    url: https://sub.vansour.top/uspre
    path: ./proxy_providers/uspre.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  usord:
    type: http
    url: https://sub.vansour.top/usord
    path: ./proxy_providers/usord.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  ustest:
    type: http
    url: https://sub.vansour.top/ustest
    path: ./proxy_providers/ustest.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

  V2:
    type: http
    url: https://sub.vansour.top/v2
    path: ./proxy_providers/v2.yaml
    interval: 1800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

# 代理分组
proxy-groups:
  - name: 主用
    type: select
    use:
      - V1
    proxies:
      - 主用 04 美国 00
      - 主用 04 英国 00
      - 主用 04 香港 00
      - 主用 04 日本 00
      - 主用 04 韩国 00
      - 主用 04 新加坡 00

  - name: Youtube
    type: select
    use:
      - ustest
    proxies:
      - 主用 04 美国 00
      - 主用 04 英国 00
      - 主用 04 香港 00
      - 主用 04 日本 00
      - 主用 04 韩国 00
      - 主用 04 新加坡 00

  - name: Github
    type: select
    use:
      - hkpre
      - uspre

  - name: Openai
    type: select
    use:
      - uspre


  # 地区分组，自动测速筛选最快节点
  - name: 主用 04 美国 00
    type: url-test
    use:
      - V2
    filter: '美国'
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true

  - name: 主用 04 英国 00
    type: url-test
    use:
      - V2
    filter: '英国'
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true

  - name: 主用 04 香港 00
    type: url-test
    use:
      - V2
    filter: '香港'
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true

  - name: 主用 04 日本 00
    type: url-test
    use:
      - V2
    filter: '日本'
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true

  - name: 主用 04 韩国 00
    type: url-test
    use:
      - V2
    filter: '韩国'
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true

  - name: 主用 04 新加坡 00
    type: url-test
    use:
      - V2
    filter: '新加坡'
    url: http://www.gstatic.com/generate_204
    interval: 300
    strategy: round-robin
    hidden: true

# 规则集
rule-providers:
  domain_category-ads-all:
    type: http
    behavior: domain
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geosite/site_category-ads-all.txt
    path: ./rule_providers/site_category-ads-all.yaml
    interval: 86400

  ip_private:
    type: http
    behavior: ipcidr
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geoip/ip_private.txt
    path: ./rule_providers/ip_private.yaml
    interval: 86400

  ip_cn:
    type: http
    behavior: ipcidr
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geoip/ip_cn.txt
    path: ./rule_providers/ip_cn.yaml
    interval: 86400

  domain_youtube:
    type: http
    behavior: domain
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geosite/site_youtube.txt
    path: ./rule_providers/site_youtube.yaml
    interval: 86400

  domain_github:
    type: http
    behavior: domain
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geosite/site_github.txt
    path: ./rule_providers/site_github.yaml
    interval: 86400

  domain_openai:
    type: http
    behavior: domain
    url: https://gitee.com/vansour/geo-rules/raw/main/geo/geosite/site_openai.txt
    path: ./rule_providers/site_openai.yaml
    interval: 86400

# 规则
rules:
  - RULE-SET,ip_private,DIRECT
  - RULE-SET,ip_cn,DIRECT
  - RULE-SET,domain_category-ads-all,REJECT
  - RULE-SET,domain_youtube,Youtube
  - RULE-SET,domain_github,Github
  - RULE-SET,domain_openai,Openai
  - MATCH,主用

unified-delay: true
tcp-concurrent: true
